# -*- coding: utf-8 -*-
"""regex_functions_interactive_tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xg7cCiMFJbHeZjClAUyn1cgCBfN-vk5u

# Regular Expressions in Python (`re`) — Interactive Notebook

This notebook is designed to **run, modify, and observe** Python regular expressions step by step.

It is based on the presentation slides including the use of `re.search()` and `re.findall()` with practical text examples.

---
## How to use this notebook
1. Run cells from top to bottom.
2. Change the patterns and texts.
3. Observe how outputs change.
4. Use the challenge cells at the end for practice.

This notebook covers:
- `re.search()`
- `re.match()`
- `re.fullmatch()`
- `re.findall()`
- `re.finditer()`
- `re.split()`
- `re.sub()`
- `re.subn()`
- `re.compile()`
- `re.escape()`
- groups, named groups, flags, anchors, quantifiers, and more
"""

import re
from pprint import pprint

def inspect_match(match):
    """Pretty-print a match object."""
    if match is None:
        print("No match")
        return
    print("Matched text :", match.group())
    print("Start index  :", match.start())
    print("End index    :", match.end())
    print("Span         :", match.span())
    print("Groups       :", match.groups())
    print("Group dict   :", match.groupdict())

def show_finditer(pattern, text, flags=0):
    print(f"PATTERN: {pattern!r}")
    print(f"TEXT   : {text!r}")
    matches = list(re.finditer(pattern, text, flags))
    print(f"TOTAL MATCHES: {len(matches)}")
    for i, m in enumerate(matches, start=1):
        print(f"  {i}. {m.group()!r} at span {m.span()}")

def divider(title=""):
    print("\n" + "=" * 80)
    print(title)
    print("=" * 80)

"""## 1) What is a Regular Expression?

A **regular expression (RegEx)** is a pattern used to search, validate, extract, split, or replace text.

Example ideas:
- Find all numbers in a sentence
- Extract emails from text
- Validate whether a string is in a required format
- Replace repeated spaces with one space
"""

text = "My 2 favorite numbers are 19 and 42."
pattern = r"\d+"

print("Text   :", text)
print("Pattern:", pattern)
print("Matches:", re.findall(pattern, text))

"""## 2) Quick RegEx symbols

Common symbols:
- `.` → any character except newline
- `\d` → digit
- `\D` → not a digit
- `\w` → word character (`a-z`, `A-Z`, `0-9`, `_`)
- `\W` → not a word character
- `\s` → whitespace
- `\S` → non-whitespace
- `^` → start of string/line
- `$` → end of string/line
- `*` → 0 or more
- `+` → 1 or more
- `?` → 0 or 1
- `{m,n}` → between `m` and `n` repetitions
- `[abc]` → one character from the set
- `[^abc]` → one character not in the set
- `(...)` → capture group
- `|` → OR
"""

samples = [
    (r".", "A"),
    (r"\d+", "Room 407"),
    (r"\w+", "Dr_C"),
    (r"\s+", "a   b"),
    (r"[aeiou]", "education"),
    (r"[^aeiou\s]", "data science"),
]

for pattern, text in samples:
    divider(f"Pattern {pattern!r} on {text!r}")
    print(re.findall(pattern, text))

"""## 3) `re.search()`

`re.search()` looks for the **first place** where the pattern appears anywhere in the string.
"""

text = "Contact us at support@example.com for help."
match = re.search(r"\S+@\S+", text)
inspect_match(match)

text = "Order ID: A-493, Status: shipped"
inspect_match(re.search(r"Status:\s+\w+", text))

"""## 4) `re.match()`

`re.match()` checks only from the **beginning** of the string.
"""

text = "Python is powerful"

print("search:", re.search(r"is", text))
print("match :", re.match(r"is", text))
print("match :", re.match(r"Python", text))

"""## 5) `re.fullmatch()`

`re.fullmatch()` succeeds only if the **entire string** matches the pattern.
"""

tests = ["CS3600", "CS-3600", "MATH101", "CS99999"]
pattern = r"[A-Z]{2,4}\d{3,4}"

for t in tests:
    ok = re.fullmatch(pattern, t)
    print(f"{t:10} ->", "VALID" if ok else "INVALID")

"""## 6) `re.findall()`

`re.findall()` returns a **list of all matches**.
"""

text = "Temperatures this week: 72F, 68F, 75F, 70F"
print(re.findall(r"\d+", text))
print(re.findall(r"\d+F", text))

text = "Emails: a@x.com, bob@test.edu, admin@site.org"
print(re.findall(r"\b[\w.-]+@[\w.-]+\.\w+\b", text))

"""## 7) `re.finditer()`

`re.finditer()` returns an **iterator of match objects**.
"""

text = "IDs: X12, Y305, Z9"
show_finditer(r"[A-Z]\d+", text)

"""## 8) `re.split()`"""

text = "apple,banana;orange | mango   grape"
parts = re.split(r"[,;|\s]+", text)
print(parts)

"""## 9) `re.sub()`"""

text = "My phone numbers are 435-555-1111 and 435-555-2222"
masked = re.sub(r"\d", "X", text)
print(masked)

text = "Too     many       spaces"
clean = re.sub(r"\s+", " ", text)
print(clean)

"""## 10) `re.subn()`"""

text = "cat bat rat mat"
new_text, count = re.subn(r"\b\wat\b", "pet", text)
print("Result      :", new_text)
print("Replacements:", count)

"""## 11) `re.compile()`"""

email_pattern = re.compile(r"\b[\w.-]+@[\w.-]+\.\w+\b")

texts = [
    "Email alice@school.edu today.",
    "No email here.",
    "Team: bob@org.com and carol@dept.net"
]

for t in texts:
    print(email_pattern.findall(t))

"""## 12) `re.escape()`"""

user_text = "price is $10.00 (limited-time)"
escaped = re.escape(user_text)

print("Original:", user_text)
print("Escaped :", escaped)
print("Literal match works?:", bool(re.search(escaped, "Today the price is $10.00 (limited-time)!")))

"""## 13) Character classes

### Predefined classes
- `\d`, `\D`
- `\w`, `\W`
- `\s`, `\S`

### Custom classes
- `[abc]`
- `[a-z]`
- `[A-Z0-9]`
- `[^0-9]`
"""

text = "Room B12 is on floor 3."

patterns = [
    r"\d",
    r"\D",
    r"\w+",
    r"\W+",
    r"[A-Z]",
    r"[A-Z]\d+",
    r"[^a-zA-Z0-9\s]+",
]

for p in patterns:
    divider(p)
    print(re.findall(p, text))

"""## 14) Quantifiers

- `*` → zero or more
- `+` → one or more
- `?` → zero or one
- `{m}` → exactly `m`
- `{m,}` → at least `m`
- `{m,n}` → between `m` and `n`
"""

text = "ha haa haaa haaaa"

patterns = [
    r"ha*",
    r"ha+",
    r"ha?",
    r"ha{2}",
    r"ha{2,3}",
]

for p in patterns:
    divider(p)
    print(re.findall(p, text))

"""## 15) Greedy vs non-greedy matching"""

text = "<title>Intro</title><title>Advanced</title>"

print("Greedy     :", re.findall(r"<title>.*</title>", text))
print("Non-greedy :", re.findall(r"<title>.*?</title>", text))

"""## 16) Anchors: `^` and `$`"""

lines = [
    "From: alice@example.com",
    "Date: today",
    "From: bob@test.org",
    "Subject: hello"
]

for line in lines:
    if re.search(r"^From:", line):
        print("Matched ->", line)

tests = ["abc123", "123abc", "abc123xyz"]
for t in tests:
    print(t, "->", bool(re.search(r"^abc123$", t)))

"""## 17) Groups"""

text = "From stephen.marquard@uct.ac.za Sat Jan 5"
match = re.search(r"@(\S+)", text)
inspect_match(match)

text = "Name: Alice, Age: 24"
match = re.search(r"Name:\s+(\w+),\s+Age:\s+(\d+)", text)

print("Whole match:", match.group(0))
print("Group 1    :", match.group(1))
print("Group 2    :", match.group(2))
print("All groups :", match.groups())

"""### Non-capturing groups
Use `(?:...)` when you want grouping without storing the result as a capture group.
"""

text = "color colour color colour"
print(re.findall(r"colou?r", text))
print(re.findall(r"colo(?:u)?r", text))

"""### Named groups"""

text = "2026-03-16"
m = re.search(r"(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})", text)
inspect_match(m)

print("Year :", m.group("year"))
print("Month:", m.group("month"))
print("Day  :", m.group("day"))

"""## 18) Alternation with `|`"""

text = "The colors are red, blue, green, and black."
print(re.findall(r"red|blue|green", text))

"""## 19) Flags

Useful flags:
- `re.I` or `re.IGNORECASE`
- `re.M` or `re.MULTILINE`
- `re.S` or `re.DOTALL`
- `re.X` or `re.VERBOSE`
"""

text = "Python python PYTHON"

print(re.findall(r"python", text))
print(re.findall(r"python", text, flags=re.IGNORECASE))

text = "Start
Middle
End"

print("Without MULTILINE:", re.findall(r"^\w+", text))
print("With MULTILINE   :", re.findall(r"^\w+", text, flags=re.MULTILINE))

text = "begin
content
end"

print("Without DOTALL:", re.findall(r"begin.*end", text))
print("With DOTALL   :", re.findall(r"begin.*end", text, flags=re.DOTALL))

pattern = re.compile(r'''
    (?P<area>\d{3})   # area code
    [-\s]?            # optional separator
    (?P<prefix>\d{3}) # prefix
    [-\s]?            # optional separator
    (?P<line>\d{4})   # line number
''', re.VERBOSE)

m = pattern.search("Call me at 435-555-0199.")
inspect_match(m)

"""## 20) Useful Match object methods"""

m = re.search(r"(\w+)@(\w+\.\w+)", "Email admin@school.edu now")
inspect_match(m)

"""## 21) Interesting Example — Extract student emails"""

text = '''
Students:
alice99@suu.edu
bob_smith@usu.edu
invalid@email
carol-lee@school.org
'''

emails = re.findall(r"[\w.-]+@[\w.-]+\.\w+", text)
pprint(emails)

"""## 22) Interesting Example — Parse log entries"""

logs = '''
2026-03-16 09:00:12 INFO Server started
2026-03-16 09:01:55 WARNING High memory usage
2026-03-16 09:03:10 ERROR Database timeout
'''

pattern = re.compile(
    r"(?P<date>\d{4}-\d{2}-\d{2})\s+"
    r"(?P<time>\d{2}:\d{2}:\d{2})\s+"
    r"(?P<level>INFO|WARNING|ERROR)\s+"
    r"(?P<message>.+)"
)

for m in pattern.finditer(logs):
    print(m.groupdict())

"""## 23) Interesting Example — Clean messy text"""

messy = "This   is   a    sentence ,   with   bad spacing  !"
step1 = re.sub(r"\s+", " ", messy)
step2 = re.sub(r"\s+([,.!?;:])", r"\1", step1)

print("Original:", messy)
print("Cleaned :", step2)

"""## 24) Interesting Example — Validate simple phone formats"""

phone_pattern = re.compile(r"^(\(?\d{3}\)?[-\s]?)\d{3}[-\s]?\d{4}$")

tests = [
    "4355551234",
    "435-555-1234",
    "(435) 555-1234",
    "435 555 1234",
    "43-555-1234"
]

for t in tests:
    print(f"{t:18} ->", bool(phone_pattern.fullmatch(t)))

"""## 25) Interesting Example — Extract hashtags and mentions"""

post = "Welcome @dr_c to #Python and #RegexPractice with @students!"
print("Mentions :", re.findall(r"@\w+", post))
print("Hashtags :", re.findall(r"#\w+", post))

"""## 26) Common mistakes students make

1. Forgetting raw strings
2. Using `match()` when they need `search()`
3. Writing greedy `.*` when a non-greedy `.*?` is needed
4. Forgetting to escape special characters
5. Making patterns too broad
"""

text = "file.txt and filext"

print("Wrong :", re.findall(r"file.txt", text))
print("Right :", re.findall(r"file\.txt", text))

"""## 27) Mini practice section
Run each cell. Then modify the regex.
"""

text = "Events happened in 1999, 2008, 2025, and 2026."
print(re.findall(r"\b\d{4}\b", text))

text = "Dr. C teaches Python at Southern Utah University in Cedar City."
print(re.findall(r"\b[A-Z][a-zA-Z]*\b", text))

text = "Data		Science

 is    fun"
print(re.sub(r"\s+", " ", text))

text = 'She said "learn regex slowly" and then "practice daily".'
print(re.findall(r'"(.*?)"', text))

"""## 28) Challenge problems for students

1. Extract all decimal numbers from a sentence
2. Validate a date in `YYYY-MM-DD` form
3. Extract the domain names from email addresses
4. Find repeated words
5. Replace every 4-digit number with `[YEAR]`
"""

challenge_text = "Prices are 10, 12.5, 99.99, and .5"
print(re.findall(r"\d+\.\d+|\d+", challenge_text))

"""## 29) Summary

You have now seen the major Python RegEx tools:
- `search`
- `match`
- `fullmatch`
- `findall`
- `finditer`
- `split`
- `sub`
- `subn`
- `compile`
- `escape`

And important RegEx ideas:
- character classes
- quantifiers
- anchors
- groups
- alternation
- flags
- greedy vs non-greedy

## 30) Optional homework ideas

1. Build a mini email extractor
2. Build a password validator
3. Parse web server logs
4. Normalize phone numbers into one standard format
5. Extract URLs from a paragraph
"""